### ISSUE TITLE
RCTJSONStringify() 

### ISSUE THREAD

**Issue by yeegr** [jayesbe/react-native-cacheable-image#19]
Just import and paste your sample and got this message

RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)

**Comment by jayesbe** [comment]
The sample is just an example for implementation and not expected to work since the URI's don't exactly exist. 

Did you try with actual image URIs?

**Comment by hgoldwire** [comment]
I see it too when Remote JS Debugging is on, I think due to this ==> https://github.com/johanneslumpe/react-native-fs/issues/191

It seems to be URL dependent, specifically for URLs with no filename extension.  Here is the same file, same mime type, with and without trailing **.jpg**.  One crashes my app, one doesn't.

**BAD**: http://d3iynnomnouqcc.cloudfront.net/e654012f-b05c-47bd-b767-9e83531bcf8c/803fdc13-8806-45ee-bcba-c5e1a3d129ec

**GOOD**: http://d3iynnomnouqcc.cloudfront.net/e654012f-b05c-47bd-b767-9e83531bcf8c/803fdc13-8806-45ee-bcba-c5e1a3d129ec.jpg

Here's a tiny sample project illustrating the problem ==> [CacheableImageTest.zip](https://github.com/jayesbe/react-native-cacheable-image/files/564321/CacheableImageTest.zip)

Perhaps changing the cacheKey in [image.js:125](https://github.com/jayesbe/react-native-cacheable-image/blob/master/image.js#L125) like so would solve it.?  

```
// const type = url.pathname.replace(/.*\.(.*)/, '$1');
// const cacheKey = SHA1(url.pathname)+'.'+type;
const cacheKey = SHA1(url.pathname) + '.cached';
```

**Edit:**
Further experimentation make me think I'm barking up the wrong tree & really we should be doing RNFS.exists before RNFS.stat due to the react-native-fs issue up top.

**Comment by jayesbe** [comment]
Yes I incorrectly assumed every image would have an extension.. that definitely wasn't a good assumption.

**Comment by jayesbe** [comment]
@hgoldwire Removed the extension from cachekey generation
