### ISSUE TITLE
What happens When the url stays the same but image in server is changed?

### ISSUE THREAD

**Issue by sudugo** [jayesbe/react-native-cacheable-image#5]
i really like this component and want to use it. But i have a silly doubt.
What happens When the url stays the same but image in server is changed?
Will it download the new image and create a new cache?

**Comment by jayesbe** [comment]
If the url stays the same then its assumed the image hasn't actually changed. The url is what defines the cache key.  Though this is an interesting question. I purposely ignore the url parameters when creating the cache key because I was using it with amazon aws with secure cloudfront urls where the url parameters would constantly change. 

I believe the best way to handle this would be to set a single parameter as part of the url as an influencer.  Perhaps we can add that as an option to the state. By specifying paramName = "_" .. then when we see that a url parameter with ?_=12345 is available.. we include that as part of the cache key.  If that value changes it would result in a different cache value.. thus forcing a new image download.

What do you think?

**Comment by hgoldwire** [comment]
I suggest that by default we cache based on the entire URL, because we don't want to consider these to be the same:
- http://graph.facebook.com/v2.7/630462897/picture?type=square&width=100&height=100
- http://graph.facebook.com/v2.7/630462897/picture?type=square&width=50&height=50

Then perhaps we accept a evalQueryString property that accepts
- true  (default)
- false
- [params]

where true means always include the query string in cacheKey, false means never consider the query string, and [params] identifies specific query string parameters we want to consider while ignoring all the rest.  In my example above we would either say true or maybe ['width', 'height'].

Thoughts?

**Comment by jayesbe** [comment]
Amazon Cloudfront url's change on every load. That wouldn't work.  Im thinking that caching should maybe also be based on the headers sent along with the initial image request. Like ETag. 

However a prop would help.. but I understand that an image may not have an extension either.. so definitely there is room for improvement.

**Comment by jayesbe** [comment]
@hgoldwire re-read your idea and agree its the best option.

**Comment by jayesbe** [comment]
@hgoldwire added useQueryParamsInCacheKey prop.

**Comment by lashae** [comment]
So, does this package respect `Etag` headers? If so, on original file change (etag change) it should invalidate cache, does it?

**Comment by jayesbe** [comment]
@lashae Etag is not being checked right now.

Looking at the code, we should be able to access Etag inside the imageDownloadBegin callback. The info argument should contain a headers property which should contain the Etag.  The problem is this Etag only comes back as part of the response, so a request needs to be made for the image just to check if the Etag was changed.  We could use the Etag as part of the cache key generation, but again it, once cached we don't make another request for the image unless the image URL is changed in some way.
