### ISSUE TITLE
Doesn't work with Redux

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jayesbe/react-native-cacheable-image#8]
I get "Warning setState(...) Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the CahceableImage component".

As we're using redux in our app, did not expect CacheableImage to be setting state. Any ideas?

**Comment by jayesbe** [comment]
Well the CacheableImage has it's own state. Maybe you can describe your implementation with redux?  I use redux too but.. I don't maintain the image state in redux.. just the image url in redux. which I pass into the CacheableImage.

**Comment by scerelli** [comment]
@GeoffreyPlitt the warning you get is not related to redux state but component one. Every component has it's own state that change inside the component itselfs, if needed. So check where you placed `react-native-cacheable-image`and what you do during the render phase. Because i using this in production and i'm not getting this warning.

**Comment by jayesbe** [comment]
@GeoffreyPlitt I am guessing this has been resolved ?  Thanks @scerelli

**Comment by amelzer** [comment]
Just a quick note for other people coming here with this issue:
I had a `<Text>` node inside the `CachableImage`that seemed to have caused the problem. (Also in a Redux app). Removing it removed the error.

**Comment by jayesbe** [comment]
@amelzer I updated the example.

Your Text node should be inside a View .. give it a shot. 

Thanks!
